project(GFW)
cmake_minimum_required(VERSION 3.5)
OPTION(WINDOWS "Build the project as windows" OFF)
OPTION(ANDROID "Build the project as android" OFF)
OPTION(X86 "Build the project as X86" ON)
OPTION(ARM "Build the project as X86" OFF)

if(ANDROID)
    set(PLATFORM android)
endif(ANDROID)
if(X86)
    set(PLATFORM X86)
endif(X86)
if(ARM)
    set(PLATFORM arm)
endif(ARM)

if(WINDOWS)
    add_definitions("-D_WIN64")
    add_definitions("-D__MINGW64__")
    add_definitions("-D_AMD64_")
    add_compile_options(-std=c++11)
endif(WINDOWS)


add_definitions("-DSIMPLE_DES=1")


if (PLATFORM STREQUAL "android")
    #set(ANDROID_NDK /czx/application/android-ndk-r19)
    #set(ANDROID_NDK /root/Android/Sdk/ndk/25.1.8937393/)
    #set(CMAKE_TOOLCHAIN_FILE $ANDROID_NDK/build/cmake/android.toolchain.cmake)
    set( CMAKE_C_COMPILER        /root/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/clang)
    set( CMAKE_CXX_COMPILER      /root/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++)
    set(target aarch64-none-linux-android24)
 
   # cmake -DCMAKE_TOOLCHAIN_FILE=/czx/application/android-ndk-r19/build/cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON -DANDROID_PLATFORM=android-14 ..
    #set(ANDROID_ABI "armeabi-v7a")
    set(ANDROID_ARM_NEON ON)
    #set(ANDROID_PLATFORM android-14)
    set(ANDROID_NDK /root/Android/Sdk/ndk/25.1.8937393/)
    #set(CMAKE_TOOLCHAIN_FILE $ANDROID_NDK/build/cmake/android.toolchain.cmake)
    message(STATUS "This is a android cmake")
    add_definitions("-DANDROID=1")
elseif (PLATFORM STREQUAL "X86")
    set(CMAKE_C_COMPILER gcc)
    set(CMAKE_CXX_COMPILER g++)
elseif (PLATFORM STREQUAL "arm")
    set( CMAKE_C_COMPILER        /data/worker/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc )
    set( CMAKE_CXX_COMPILER      /data/worker/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++ )
    SET( CMAKE_CXX_FLAGS           "${ARM_C_CXX_FLAGS} "   CACHE STRING "c++ flags" )
    SET( CMAKE_C_FLAGS             "${ARM_C_CXX_FLAGS} "   CACHE STRING "c flags" )
    set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS}  ")
endif ()

set(CMAKE_CXX_FLAGS_DEBUG   "$ENV{CXXFLAGS} -O0 -g -ggdb")
set(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3 -DNDEBUG")
set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -Wall -std=c++11 -fpermissive -fno-strict-aliasing -fopenmp")
set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -Wall  -fopenmp")
if(ANDROID)
SET( CMAKE_C_FLAGS             "${ARM_C_FLAGS} --target=armv7-none-linux-androideabi24" )
set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} --target=armv7-none-linux-androideabi24")
set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} --sysroot=/root/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
-fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 \
 -mthumb -Wformat -Werror=format-security  -std=c++11 -fno-limit-debug-info  -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment \
-Wl,--fatal-warnings -Wl,--gc-sections -Wl,--no-undefined -Qunused-arguments")
endif(ANDROID)

include_directories(${CMAKE_SOURCE_DIR}/server)
link_directories(${LIBRARY_OUTPUT_PATH})
link_directories(${CMAKE_SOURCE_DIR}/server)

#add_subdirectory(server)
#add_subdirectory(client)

#add_subdirectory(server_rand)
#add_subdirectory(client_rand)
#add_subdirectory(forward_server)
#add_subdirectory(forward_dst)
add_subdirectory(forward_v2_client)
add_subdirectory(forward_v2_server)
#add_subdirectory(server_test)
#add_subdirectory(client_test)
